services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
    tty: true
    hostname: web
    volumes:
      - .:/firebase
      - node_home:/home/node
    ports:
      - "9005:9005"

volumes:
  node_home:
